export const BUSINESS_TYPE_OPTIONS = [
  { group: "Food & Drink", options: [
    { value: "restaurant", label: "Restaurant" },
    { value: "cafe", label: "Café / Coffee Shop" },
    { value: "bar", label: "Bar / Pub" },
    { value: "bakery", label: "Bakery / Pastry Shop" },
    { value: "pizza", label: "Pizza Restaurant" },
    { value: "fast_food", label: "Fast Food / Quick Service" },
    { value: "food_truck", label: "Food Truck" },
    { value: "catering", label: "Catering Company" },
    { value: "winery_brewery", label: "Winery / Brewery / Distillery" },
    { value: "deli", label: "Deli / Sandwich Shop" },
    { value: "ice_cream", label: "Ice Cream / Dessert Shop" },
    { value: "juice_bar", label: "Juice Bar / Smoothie Shop" },
  ]},
  { group: "Automotive", options: [
    { value: "car_dealer_new", label: "New Car Dealership" },
    { value: "car_dealer_used", label: "Used Car Dealership" },
    { value: "auto_repair", label: "Auto Repair / Mechanic" },
    { value: "tire_shop", label: "Tire Shop" },
    { value: "body_shop", label: "Auto Body / Collision Repair" },
    { value: "car_wash", label: "Car Wash / Auto Detailing" },
    { value: "oil_change", label: "Oil Change / Quick Lube" },
    { value: "trailer_dealer", label: "Trailer Dealership" },
    { value: "rv_dealer", label: "RV / Motorhome Dealer" },
    { value: "motorcycle_dealer", label: "Motorcycle Dealership" },
    { value: "auto_parts", label: "Auto Parts Store" },
    { value: "towing", label: "Towing / Roadside Assistance" },
  ]},
  { group: "Health & Medical", options: [
    { value: "dentist", label: "Dental Practice" },
    { value: "doctor", label: "Doctor / Primary Care" },
    { value: "chiropractor", label: "Chiropractor" },
    { value: "optometrist", label: "Eye Care / Optometrist" },
    { value: "physical_therapy", label: "Physical Therapy" },
    { value: "urgent_care", label: "Urgent Care" },
    { value: "pharmacy", label: "Pharmacy" },
    { value: "mental_health", label: "Mental Health / Therapy" },
    { value: "dermatologist", label: "Dermatology" },
    { value: "med_spa", label: "Med Spa / Aesthetics" },
  ]},
  { group: "Beauty & Personal Care", options: [
    { value: "hair_salon", label: "Hair Salon" },
    { value: "barbershop", label: "Barbershop" },
    { value: "nail_salon", label: "Nail Salon" },
    { value: "spa_massage", label: "Spa / Massage Therapy" },
    { value: "tattoo_studio", label: "Tattoo Studio / Piercing" },
    { value: "lash_brow", label: "Lash / Brow Studio" },
  ]},
  { group: "Home Services", options: [
    { value: "plumber", label: "Plumbing" },
    { value: "electrician", label: "Electrician" },
    { value: "hvac", label: "HVAC" },
    { value: "roofer", label: "Roofing" },
    { value: "landscaper", label: "Landscaping / Lawn Care" },
    { value: "house_cleaner", label: "House Cleaning" },
    { value: "mover", label: "Moving Company" },
    { value: "pest_control", label: "Pest Control" },
    { value: "contractor", label: "General Contractor / Remodeling" },
    { value: "handyman", label: "Handyman Service" },
    { value: "pool_service", label: "Pool Service" },
    { value: "painter", label: "Painting Contractor" },
    { value: "flooring", label: "Flooring Installation" },
  ]},
  { group: "Retail", options: [
    { value: "clothing_store", label: "Clothing / Apparel" },
    { value: "gift_shop", label: "Gift Shop / Boutique" },
    { value: "jewelry_store", label: "Jewelry Store" },
    { value: "hardware_store", label: "Hardware Store" },
    { value: "pet_store", label: "Pet Store" },
    { value: "bookstore", label: "Bookstore" },
    { value: "furniture_store", label: "Furniture Store" },
    { value: "sporting_goods", label: "Sporting Goods / Outdoor" },
    { value: "electronics", label: "Electronics Store" },
    { value: "antique_shop", label: "Antique / Vintage Shop" },
  ]},
  { group: "Professional Services", options: [
    { value: "law_firm", label: "Law Firm" },
    { value: "accountant", label: "Accounting / CPA" },
    { value: "real_estate", label: "Real Estate Agency" },
    { value: "insurance", label: "Insurance Agency" },
    { value: "financial_advisor", label: "Financial Advisor" },
    { value: "marketing_agency", label: "Marketing Agency" },
    { value: "it_services", label: "IT Services" },
  ]},
  { group: "Hospitality & Travel", options: [
    { value: "hotel", label: "Hotel / Motel" },
    { value: "bnb", label: "Bed & Breakfast / Inn" },
    { value: "vacation_rental", label: "Vacation Rental" },
    { value: "event_venue", label: "Event / Wedding Venue" },
  ]},
  { group: "Education & Childcare", options: [
    { value: "daycare", label: "Daycare / Preschool" },
    { value: "tutoring", label: "Tutoring Center" },
    { value: "driving_school", label: "Driving School" },
    { value: "music_school", label: "Music / Dance / Arts School" },
    { value: "martial_arts", label: "Martial Arts School" },
  ]},
  { group: "Entertainment & Fitness", options: [
    { value: "gym", label: "Gym / Fitness Center" },
    { value: "yoga_studio", label: "Yoga / Pilates Studio" },
    { value: "golf_course", label: "Golf Course" },
    { value: "bowling", label: "Bowling / Entertainment Center" },
    { value: "escape_room", label: "Escape Room" },
    { value: "entertainment_venue", label: "Entertainment Venue" },
  ]},
  { group: "Pets", options: [
    { value: "veterinarian", label: "Veterinary Clinic" },
    { value: "pet_grooming", label: "Pet Grooming" },
    { value: "pet_boarding", label: "Pet Boarding / Doggy Daycare" },
    { value: "dog_training", label: "Dog Training" },
  ]},
  { group: "Industrial & Commercial", options: [
    { value: "self_storage", label: "Self Storage Facility" },
    { value: "moving_storage", label: "Moving & Storage Company" },
    { value: "trucking", label: "Trucking / Freight / Logistics" },
    { value: "commercial_cleaning", label: "Commercial Cleaning" },
    { value: "laundromat", label: "Laundromat / Dry Cleaning" },
    { value: "print_shop", label: "Print Shop / Sign Shop" },
    { value: "welding", label: "Welding / Metal Fabrication" },
    { value: "construction", label: "Construction Company" },
    { value: "concrete_paving", label: "Concrete / Paving" },
    { value: "farm_equipment", label: "Farm / Tractor Equipment Dealer" },
    { value: "industrial_supply", label: "Industrial / Trade Supply Store" },
    { value: "commercial_real_estate", label: "Commercial Real Estate" },
    { value: "warehouse", label: "Warehouse / Distribution" },
    { value: "auto_auction", label: "Auto Auction" },
    { value: "equipment_rental", label: "Equipment Rental" },
    { value: "waste_management", label: "Waste Management / Dumpster Rental" },
  ]},
];
